// <auto-generated />
namespace WebApiFundamental.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class adderrorlogger : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adderrorlogger));
        
        string IMigrationMetadata.Id
        {
            get { return "202007252136274_add-errorlogger"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
